[tools]
node = "prefix:22"
pnpm = "prefix:9"

# The tools listed below are used in the project.
# However, you probably installed them globally.
# @vscode/vsce = "prefix:3"
# ovsx         = "prefix:0"
