# c

.DEFAULT:
.DELETE_ON_ERROR:
.EXPORT_ALL_VARIABLES:
.IGNORE:
.INTERMEDIATE:
.LOW_RESOLUTION_TIME:
.NOTPARALLEL:
.ONESHELL:
.PHONY:
.POSIX:
.PRECIOUS:
.SECONDARY:
.SECONDEXPANSION:
.SILENT:
.SUFFIXES:

$(patsubst %, r)

r:
	-e
	@e
	+e
	e \
	e
# e \
# e

define v
export
ifdef
ifeq
ifndef
ifneq
include
override
private
undefine
unexport
vpath

ifeq
else
endif
