c0("// c")
c0("/// c")
c0("/* c */")
c0("/** c */")

s0('"'); s1("s"); s0('"')
s0('"'); s1("s"); s0('"'); p1("s")
s0('"'); s1("s"); s0('"'); p1("_s")
s0("'"); s1("s"); s0("'")
s0("'"); s1("s"); s0("'"); p1("s")
s0("'"); s1("s"); s0("'"); p1("_s")
s0('R"('); s1("s"); s0(')"')
s0('R"('); s1("s"); s0(')"'); p1("s")
s0('R"('); s1("s"); s0(')"'); p1("_s")

p1("true")
p1("false")
p1("NULL")
p1("nullptr")

p1("0")
p1("0b0")
p1("0B0")
p1("0e0")
p1("0E0")
p1("0f")
p1("0F")
p1("0l")
p1("0L")
p1("0ll")
p1("0LL")
p1("0u")
p1("0U")
p1("0ull")
p1("0ULL")
p1("0x0")
p1("0X0")
p1("0"); p0("."); p1("0")
p1("0"); p0("'"); p1("0")
p1("0_s")

p0("+")
p0("-")
p0("*")
p0("/")
p0("%")

p0("++")
p0("--")

p0("==")
p0("!=")
p0("<")
p0(">")
p0("<=")
p0(">=")

p0("&&")
p0("||")
p0("!")

p0("&")
p0("|")
p0("^")
p0("~")
p0("<<")
p0(">>")

p0("=")
p0("+=")
p0("-=")
p0("*=")
p0("/=")
p0("%=")
p0("&=")
p0("|=")
p0("^=")
p0("<<=")
p0(">>=")

p0("?")
p0(":")

p0(",")
p0(";")

p1("std"); p0("::"); p1("a"); p0(";")
p1("v"); p0("::"); p1("v"); p0("();")

p1("a"); p0("."); p1("a"); p0(";")
p1("a"); p0("->"); p1("a"); p0("();")

p0("alignas("); p1("a"); p0(")")
p0("alignof("); p1("a"); p0(")")
p0("delete")
p0("delete[]")
p0("new")
p0("noexcept")
p0("sizeof("); p1("a"); p0(")")
p0("sizeof...()")
p0("typeid("); p1("a"); p0(")")

p0("#elif")
p0("#else")
p0("#endif")
p0("#if")
p0("#ifdef")
p0("#ifndef")
p0('#include "'); p1("s"); p0('"')
p0("#include <"); p1("s"); p0(">")
p0('#include_next "'); p1("s"); p0('"')
p0("#pragma")
p0("#pragma mark")
p0("#undef"); p1("a")

p0("#if defined()")
p0("#endif")

p0("#error")
p0("#warning")
p0("#line")

p0("auto")
p0("char")
p0("double")
p0("float")
p0("int")
p0("long int")
p0("long long int")
p0("short int")
p0("signed int")
p0("unsigned int")
p0("void")

p0("blkcnt_t")
p0("blksize_t")
p0("caddr_t")
p0("clock_t")
p0("daddr_t")
p0("dev_t")
p0("div_t")
p0("fixpt_t")
p0("gid_t")
p0("id_t")
p0("in_addr_t")
p0("in_port_t")
p0("ino_t")
p0("int_fast8_t")
p0("int_fast16_t")
p0("int_fast32_t")
p0("int_fast64_t")
p0("int_least8_t")
p0("int_least16_t")
p0("int_least32_t")
p0("int_least64_t")
p0("int8_t")
p0("int16_t")
p0("int32_t")
p0("int64_t")
p0("intmax_t")
p0("intptr_t")
p0("key_t")
p0("mode_t")
p0("nlink_t")
p0("off_t")
p0("pid_t")
p0("qaddr_t")
p0("quad_t")
p0("segsz_t")
p0("size_t")
p0("ssize_t")
p0("suseconds_t")
p0("swblk_t")
p0("time_t")
p0("u_char")
p0("u_int")
p0("u_long")
p0("u_quad_t")
p0("u_short")
p0("uid_t")
p0("uint")
p0("uint_fast8_t")
p0("uint_fast16_t")
p0("uint_fast32_t")
p0("uint_fast64_t")
p0("uint_least8_t")
p0("uint_least16_t")
p0("uint_least32_t")
p0("uint_least64_t")
p0("uint8_t")
p0("uint16_t")
p0("uint32_t")
p0("uint64_t")
p0("uintmax_t")
p0("uintptr_t")
p0("useconds_t")
p0("ushort")

p0("pthread_t")
p0("pthread_attr_t")
p0("pthread_cond_t")
p0("pthread_condattr_t")
p0("pthread_key_t")
p0("pthread_mutex_t")
p0("pthread_mutexattr_t")
p0("pthread_once_t")
p0("pthread_rwlock_t")
p0("pthread_rwlockattr_t")

p0("concept")
p0("constinit")
p0("export")
p0("module")
p0("requires")
p0("typedef")

p0("const int")
p0("extern")
p0("register")
p0("restrict")
p0("static")
p0("thread_local")
p0("volatile int")

p0("const")
p0("const noexcept")
p0("consteval")
p0("constexpr")
p0("explicit")
p0("final")
p0("friend")
p0("inline")
p0("mutable")
p0("override")
p0("virtual")
p0("volatile")

p0("const int"); p1("a"); p0("() {};")
p0("consteval int"); p1("a"); p0("() {};")
p0("constexpr int"); p1("a"); p0("() {};")
p0("explicit int"); p1("a"); p0("() {};")
p0("extern int"); p1("a"); p0("() {};")
p0("friend int"); p1("a"); p0("() {};")
p0("inline int"); p1("a"); p0("() {};")
p0("mutable int"); p1("a"); p0("() {};")
p0("register int"); p1("a"); p0("() {};")
p0("restrict int"); p1("a"); p0("() {};")
p0("static int"); p1("a"); p0("() {};")
p0("thread_local int"); p1("a"); p0("() {};")
p0("virtual int"); p1("a"); p0("() {};")
p0("volatile int"); p1("a"); p0("() {};")

p0("break")
p0("case")
p0("catch")
p0("co_await")
p0("co_return")
p0("co_yield")
p0("continue")
p0("default")
p0("do")
p0("else")
p0("for")
p0("goto")
p0("goto")
p0("if")
p0("return")
p0("switch")
p0("throw")
p0("try")
p0("while")

p0("private:")
p0("protected:")
p0("public:")

p0("decltype();")

p0("class {};")
p0("enum {};")
p0("extern"); s0('""'); p0("{};")
p0("struct {};")
p0("union {};")

p0("struct"); p1("a"); p0("final {}")
p0("struct"); p1("a"); p0(": a, a {};")
p0("struct"); p1("a"); p0(": private a {};")
p0("struct"); p1("a"); p0(": protected a {};")
p0("struct"); p1("a"); p0(": public a {};")
p0("struct"); p1("a"); p0(": virtual a {};")

p0("class"); p1("a"); p0("final {}")
p0("class"); p1("a"); p0(": a, a {};")
p0("class"); p1("a"); p0(": private a {};")
p0("class"); p1("a"); p0(": protected a {};")
p0("class"); p1("a"); p0(": public a {};")
p0("class"); p1("a"); p0(": virtual a {};")

p0("namespace"); p1("a"); p0("{};")
p0("namespace"); p1("a"); p0("= a;")
p0("using namespace"); p1("a"); p0(";")

p0("template class"); p1("a"); p0("::a<>;")
p0("template class <a::a>;")
p0("template<class a, a::a>;")

p0("int["); p1("0"); p0("];")
p0("int (*"); p1("a"); p0(")();")
p0("for ("); p1("a"); p0(":"); p1("a"); p0(") {};")

p1("asm"); p0("("); s0('"'); s1("s"); s0('"'); p0(": ());")
p1("static_assert"); p0("("); p1("a"); p0(");")

p0("[](){}();")
p0("[]() -> int {};")
p0("[](a...) {};")

p0("int"); p1("a"); p0("(int *"); p1("a"); p0(", int &"); p1("a"); p0("[]) {};")
p0("int"); p1("a"); p0("(_In_ int"); p1("a"); p0(", _Out_ int"); p1("a"); p0(") {};")
p0("int"); p1("a"); p0("(std::a"); p1("a"); p0(", a"); p1("a"); p0(") {};")
p0("int"); p1("a"); p0("::"); p1("a"); p0("();")
p0("a"); p1("a"); p0("() {};")
p0("std::a<>"); p1("a"); p0("() {};")
p0("auto"); p1("a"); p0("() -> std::a {};")
p0("auto"); p1("a"); p0("() -> decltype(a) {};")
p0("[[a::a]] int"); p1("a"); p0("();")

p0("using"); p1("a"); p0("= void ()();")
p0("using"); p1("a"); p0("= std::a;")

p0("() {")
p1("start"); p0(":")
p0("switch () {")
p0("case:")
p0("default:")
p0("}")
p0("};")

p0("class {")
p1("a"); p0("() :"); p1("a"); p0("() {}")
p1("a"); p0("() = default;")
p1("a"); p0("() = delete;")
p1("a"); p0("() = override;")
p1("a"); p0("operator"); p1("()"); p0("() {};")
p1("a"); p0("operator"); p1("[]"); p0("() {};")
p1("~a"); p0("() {}")
p0("};")
