name: Publish

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        re=$(curl --silent --header "Accept: application/json" "https://api.github.com/users/github-actions%5Bbot%5D")
        lo=$(echo "$re" | jq --raw-output ".login")
        id=$(echo "$re" | jq --raw-output ".id")
        git config --global user.name "$lo"
        git config --global user.email "$id+$lo@users.noreply.github.com"

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install Extension Dependencies
      working-directory: extension
      run: pnpm install --frozen-lockfile

    - name: Install Site Dependencies
      working-directory: site
      run: pnpm install --frozen-lockfile

    - name: Build Site
      working-directory: site
      run: pnpm build

    - name: Publish Site
      working-directory: site/dist
      run: |
        un=$(git config --get user.name)
        ru="${{github.server_url}}/${{github.repository}}.git"
        ru=$(echo "$ru" | sed "s#https://#https://$un:${{github.token}}@#")

        td=$(mktemp -d)
        git clone --quiet --no-checkout --single-branch --branch gh-pages "$ru" "$td"

        mv "$td/.git" .
        git add .

        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit --quiet --message "$(date --utc)"
          git push
        fi
